### ISSUE TITLE
Maximum number of 15 lines displayed

### ISSUE THREAD

**Issue by tomek7667** [jemag/telescope-diff.nvim#2]
Hi, I'm kinda new to nvim and it's probably something on me / my understanding of windows in nvim etc., but maybe you will know whether it's the issue of the plugin *(btw i really like the idea)* or something on my side.

![image](https://github.com/jemag/telescope-diff.nvim/assets/38402753/7ec3efc0-3bfe-4718-9440-4eda581b9166)

I have this problem when I compare two files, there is maximum of 15 lines displayed which makes it unusable for longer files. I have tried to set in my lua init files the `vim.g.telescope_diff_max_lines = 10000` but it didn't change anything.

Any ideas?

**Comment by jemag** [comment]
if you mean the `80 lines` at the bottom not being displayed, this is totally normal. By default vim will only show lines that have a difference in this mode. Other lines will be hidden inside of folds.

See `help folds` for more information. You can also press `zR` to open all folds in normal mode.

**Comment by tomek7667** [comment]
Thank you, and sorry for wasting your time.
